In [32]:
#install pandas
import pandas as pd

In [33]:
#version check
pd.__version__

'2.2.2'

In [34]:
# read data
df = pd.read_csv('/content/air_traffic_data.csv')

In [35]:
# to check top 5 data
df.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Adjusted Activity Type Code,Adjusted Passenger Count,Year,Month
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271,Deplaned,27271,2005,July
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131,Enplaned,29131,2005,July
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415,Thru / Transit * 2,10830,2005,July
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156,Deplaned,35156,2005,July
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090,Enplaned,34090,2005,July

In [36]:
# summary of datasets
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15007 entries, 0 to 15006
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Activity Period              15007 non-null  int64
 1   Operating Airline            15007 non-null  object
 2   Operating Airline IATA Code  14953 non-null  object
 3   Published Airline            15007 non-null  object
 4   Published Airline IATA Code  14953 non-null  object
 5   GEO Summary                  15007 non-null  object
 6   GEO Region                   15007 non-null  object
 7   Activity Type Code           15007 non-null  object
 8   Price Category Code          15007 non-null  object
 9   Terminal                     15007 non-null  object
 10  Boarding Area                15007 non-null  object
 11  Passenger Count              15007 non-null  int64
 12  Adjusted Activity Type Code  15007 non-null  object
 13  Adjusted Passenger Count     15007 non-null  int64
 14  Year                         15007 non-null  int64
 15  Month                        15007 non-null  object
dtypes: int64(4), object(12)
memory usage: 1.8+ MB

In [37]:
# to know the column
df.columns

Index(['Activity Period', 'Operating Airline', 'Operating Airline IATA Code',
       'Published Airline', 'Published Airline IATA Code', 'GEO Summary',
       'GEO Region', 'Activity Type Code', 'Price Category Code', 'Terminal',
       'Boarding Area', 'Passenger Count', 'Adjusted Activity Type Code',
       'Adjusted Passenger Count', 'Year', 'Month'],
      dtype='object')

In [38]:
# to know data types
df.dtypes

Activity Period                 int64
Operating Airline              object
Operating Airline IATA Code    object
Published Airline              object
Published Airline IATA Code    object
GEO Summary                    object
GEO Region                     object
Activity Type Code             object
Price Category Code            object
Terminal                       object
Boarding Area                  object
Passenger Count                 int64
Adjusted Activity Type Code    object
Adjusted Passenger Count        int64
Year                            int64
Month                          object
dtype: object

In [39]:
# Combine Year and Month into a real datetime column
df['Date'] = pd.to_datetime(df['Year'].astype(str) + ' ' + df['Month'], format='%Y %B')

df.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Adjusted Activity Type Code,Adjusted Passenger Count,Year,Month,Date
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271,Deplaned,27271,2005,July,2005-07-01
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131,Enplaned,29131,2005,July,2005-07-01
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415,Thru / Transit * 2,10830,2005,July,2005-07-01
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156,Deplaned,35156,2005,July,2005-07-01
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090,Enplaned,34090,2005,July,2005-07-01

In [40]:
df.dtypes

Activity Period                         int64
Operating Airline                      object
Operating Airline IATA Code            object
Published Airline                      object
Published Airline IATA Code            object
GEO Summary                            object
GEO Region                             object
Activity Type Code                     object
Price Category Code                    object
Terminal                               object
Boarding Area                          object
Passenger Count                         int64
Adjusted Activity Type Code            object
Adjusted Passenger Count                int64
Year                                    int64
Month                                  object
Date                           datetime64[ns]
dtype: object

In [41]:
# to check duplicate
duplicate_rows = df.duplicated().sum()
print('duplicate_rows',duplicate_rows)

duplicate_rows 0

In [42]:
# to check missing value
missing_values = df.isnull().sum()
print('missing_values:', missing_values)

missing_values: Activity Period                 0
Operating Airline               0
Operating Airline IATA Code    54
Published Airline               0
Published Airline IATA Code    54
GEO Summary                     0
GEO Region                      0
Activity Type Code              0
Price Category Code             0
Terminal                        0
Boarding Area                   0
Passenger Count                 0
Adjusted Activity Type Code     0
Adjusted Passenger Count        0
Year                            0
Month                           0
Date                            0
dtype: int64

In [43]:
# to replace null value instead of missing value
df['Operating Airline IATA Code'].fillna('NaN', inplace=True)
df['Published Airline IATA Code'].fillna('NaN', inplace=True)

/tmp/ipython-input-3528352370.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3528352370.py:3: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [44]:
#To check missing value
missing_values = df.isnull().sum()
print('missing_values:', missing_values)

missing_values: Activity Period                0
Operating Airline              0
Operating Airline IATA Code    0
Published Airline              0
Published Airline IATA Code    0
GEO Summary                    0
GEO Region                     0
Activity Type Code             0
Price Category Code            0
Terminal                       0
Boarding Area                  0
Passenger Count                0
Adjusted Activity Type Code    0
Adjusted Passenger Count       0
Year                           0
Month                          0
Date                           0
dtype: int64

In [45]:
df.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Adjusted Activity Type Code,Adjusted Passenger Count,Year,Month,Date
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271,Deplaned,27271,2005,July,2005-07-01
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131,Enplaned,29131,2005,July,2005-07-01
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415,Thru / Transit * 2,10830,2005,July,2005-07-01
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156,Deplaned,35156,2005,July,2005-07-01
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090,Enplaned,34090,2005,July,2005-07-01

1. How has passenger traffic changed over time?
  • Columns: Activity Period, Passenger Count, Year, Month
  • Graph: Line Chart
  • Description: Plot passenger count over time to identify trends and seasonal patterns.

In [46]:
# Convert Activity Period to datetime
df['Activity Period'] = pd.to_datetime(df['Activity Period'], format='%Y%m')

# Check the result
df[['Activity Period']].head()

  Activity Period
0      2005-07-01
1      2005-07-01
2      2005-07-01
3      2005-07-01
4      2005-07-01

In [47]:
# line chart analysis
import plotly.express as px

df['Activity Period'] = pd.to_datetime(df['Activity Period'], format='%Y%m')
df['Activity Period Label'] = df['Activity Period'].dt.strftime('%Y-%b')

monthly_passengers = df.groupby(['Activity Period', 'Activity Period Label'])['Passenger Count'].sum().reset_index()

fig = px.line(
    monthly_passengers,
    x='Activity Period Label',
    y='Passenger Count',
    title='✈️ Passenger Traffic Over Time',
    labels={'Activity Period Label': 'Date', 'Passenger Count': 'Total Passengers'},
    markers=True
)

# Customize layout
fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    xaxis_tickangle=-45,
    )
fig.show()

2. Which airlines have the highest passenger counts?
• Columns: Operating Airline, Passenger Count
• Graph: Bar Chart
• Description: Compare the total passenger count for each airline

In [48]:
# Group by airline and sum passenger counts
airline_totals = df.groupby('Operating Airline')['Passenger Count'].sum().reset_index()

# Sort by passenger count in descending order and get top 15 airlines
top_airlines = airline_totals.sort_values('Passenger Count', ascending=False).head(15)

# Create bar chart
fig = px.bar(
    top_airlines,
   x='Passenger Count',
   y='Operating Airline',
    orientation='h',
    title='✈️ Top Airlines by Passenger Count',
    labels={'Passenger Count': 'Total Passengers', 'Operating Airline': 'Airline'},
    color='Passenger Count',
    color_continuous_scale='viridis'
)


fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    yaxis={'categoryorder': 'total ascending'},
    height=600
)


fig.update_xaxes(tickformat=',')
fig.show()

3. What is the geographic distribution of passengers?
• Columns: GEO Summary, GEO Region, Passenger Count
• Graph: Pie Chart or Choropleth Map
• Description: Show the proportion of passengers from different geographic regions or a map
highlighting passenger counts by region

In [49]:
# Geographic distribution by GEO Summary (Domestic vs International)
geo_summary = df.groupby('GEO Summary')['Passenger Count'].sum().reset_index()

fig1 = px.pie(
    geo_summary,
    values='Passenger Count',
    names='GEO Summary',
    title='🌍 Passenger Distribution: Domestic vs International',
    color='GEO Summary',
    color_discrete_map={'Domestic': '#1f77b4', 'International': '#ff7f0e'}
)
fig1.update_layout(template='plotly_white', title_x=0.5)
fig1.show()

In [50]:
# Geographic distribution by GEO Region
geo_region = df.groupby('GEO Region')['Passenger Count'].sum().reset_index()
geo_region = geo_region.sort_values('Passenger Count', ascending=False)

# Create pie chart for GEO Region
fig2 = px.pie(
    geo_region,
    values='Passenger Count',
    names='GEO Region',
    title='🌍 Passenger Distribution by Geographic Region',
    color='GEO Region',
    hover_data=['Passenger Count'],
    labels={'Passenger Count': 'Passengers'}
)

fig2.update_layout(
    template='plotly_white',
    title_x=0.5,
    height=600
)

# Show values and percentages on the chart
fig2.update_traces(
    textposition='inside',
    textinfo='percent+label',
    insidetextorientation='radial'
)

fig2.show()

In [51]:
import plotly.express as px
import pandas as pd

# Filter data for International and Domestic only
filtered_df = df[df['GEO Summary'].isin(['International', 'Domestic'])]

# Group by GEO Region and GEO Summary
geo_choropleth = filtered_df.groupby(['GEO Region', 'GEO Summary'])['Passenger Count'].sum().reset_index()

# Create mapping from GEO Region to country/continent codes
region_mapping = {
    'US': 'USA',
    'Canada': 'CAN',
    'Mexico': 'MEX',
    'Central America': 'CYM',
    'Europe': 'EUU',
    'Asia': 'ASI',
    'Australia / Oceania': 'AUS'
}


geo_choropleth['Country_Code'] = geo_choropleth['GEO Region'].map(region_mapping)

# Create choropleth map
fig = px.choropleth(
    geo_choropleth,
    locations='Country_Code',
    color='Country_Code',
    hover_name='GEO Region',
    hover_data={'GEO Summary': True, 'Passenger Count': True, 'Country_Code': False},
    title='🌍 Passenger Distribution by Geographic Region (Choropleth Map)',
    color_continuous_scale='viridis',
    scope='world'
)

fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    height=600,
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type='equirectangular'
    )
)

# Add annotations for regions without standard country codes
fig.add_annotation(
    x=0.5, y=0.02,
    xref='paper', yref='paper',
    text="Note: Asia and Europe shown as aggregated regions",
    showarrow=False,
    bgcolor='white',
    bordercolor='black',
    borderwidth=1
)

fig.show()

In [52]:
import plotly.graph_objects as go

filtered_df = df[df['GEO Summary'].isin(['International', 'Domestic'])]

# Create separate dataframes for Domestic and International
domestic_data = filtered_df[filtered_df['GEO Summary'] == 'Domestic'].groupby('GEO Region')['Passenger Count'].sum().reset_index()
international_data = filtered_df[filtered_df['GEO Summary'] == 'International'].groupby('GEO Region')['Passenger Count'].sum().reset_index()

# Sort regions by total passenger count
all_regions = filtered_df.groupby('GEO Region')['Passenger Count'].sum().sort_values(ascending=False).index

# Create the figure
fig = go.Figure()

# Add Domestic bars
fig.add_trace(go.Bar(
    name='Domestic',
    x=domestic_data['GEO Region'],
    y=domestic_data['Passenger Count'],
    marker_color='#1f77b4',
    text=domestic_data['Passenger Count'],
    texttemplate='%{text:,}',
    textposition='outside'
))

# Add International bars
fig.add_trace(go.Bar(
    name='International',
    x=international_data['GEO Region'],
    y=international_data['Passenger Count'],
    marker_color='#ff7f0e',
    text=international_data['Passenger Count'],
    texttemplate='%{text:,}',
    textposition='outside'
))


fig.update_layout(
    title='🌍 Passenger Count by Geographic Region - Domestic vs International',
    xaxis_title='Geographic Region',
    yaxis_title='Total Passengers',
    template='plotly_white',
    title_x=0.5,
    height=500,
    xaxis={'categoryorder': 'array', 'categoryarray': all_regions},
    barmode='group',  # This creates grouped bars
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)


fig.update_yaxes(tickformat=',')

fig.show()

4. How do passenger counts vary by terminal and boarding area?
•Columns: Terminal, Boarding Area, Passenger Count
•Graph: Stacked Bar Chart or Heatmap
•Description: Compare passenger counts across different terminals and boarding areas.

In [53]:
# Group by Terminal and Boarding Area
terminal_boarding = df.groupby(['Terminal', 'Boarding Area'])['Passenger Count'].sum().reset_index()
terminal_boarding

        Terminal Boarding Area  Passenger Count
0  International             A         57670570
1  International             G         57613844
2          Other         Other              200
3     Terminal 1             A           409316
4     Terminal 1             B         67373108
5     Terminal 1             C         42271640
6     Terminal 2             D         34060240
7     Terminal 3             E         40886909
8     Terminal 3             F        138526673

In [54]:
# Group by Terminal and Boarding Area
terminal_boarding = df.groupby(['Terminal', 'Boarding Area'])['Passenger Count'].sum().reset_index()

# Create a pivot table for heatmap
pivot_table = terminal_boarding.pivot_table(
    values='Passenger Count',
    index='Terminal',
    columns='Boarding Area',
    fill_value=0
)


# Create heatmap
fig1 = px.imshow(
    pivot_table,
    title='🔥 Passenger Distribution: Terminal vs Boarding Area (Heatmap)',
    labels=dict(x="Boarding Area", y="Terminal", color="Passengers"),
    #color_continuous_scale=colorscale,
    #color_continuous_scale = 'viridis',
    color_continuous_scale='reds',
    aspect="auto"
)

fig1.update_layout(template='plotly_white', title_x=0.5)
fig1.show()

5. What is the impact of different activity types on passenger counts?
•Columns: Activity Type Code, Passenger Count
•Graph: Bar Chart
•Description: Compare passenger counts for different activity types (e.g., domestic, international).

In [55]:
# Group by Activity Type Code and sum passenger counts
activity_totals = df.groupby('Activity Type Code')['Passenger Count'].sum().reset_index()

# Sort by passenger count in descending order
activity_totals = activity_totals.sort_values('Passenger Count', ascending=False)

# Create bar chart
fig = px.bar(
    activity_totals,
    x='Activity Type Code',
    y='Passenger Count',
    title='📊 Passenger Count by Activity Type',
    labels={'Passenger Count': 'Total Passengers', 'Activity Type Code': 'Activity Type'},
    color='Activity Type Code',
    color_discrete_sequence=px.colors.qualitative.Set3
)

# Update layout for better readability
fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    xaxis_tickangle=0,
    height=600
)

# Format y-axis to show numbers with commas
fig.update_yaxes(tickformat=',')

# Add value labels on bars
fig.update_traces(
    texttemplate='%{y:,}',
    textposition='outside'
)
fig.show()

6. How do price categories affect passenger counts?
•Columns: Price Category Code, Passenger Count
•Graph: Bar Chart
•Description: Compare passenger counts across different price categories.

In [56]:
# Group by Price Category Code and sum passenger counts
price_totals = df.groupby('Price Category Code')['Passenger Count'].sum().reset_index()


# Create bar chart
fig = px.bar(
    price_totals,
    x='Price Category Code',
    y='Passenger Count',
    title='💰 Passenger Count by Price Category',
    labels={'Passenger Count': 'Total Passengers', 'Price Category Code': 'Price Category'},
    color='Price Category Code',
    color_discrete_sequence=px.colors.qualitative.Bold
)


fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    xaxis_tickangle=0,
    height=600
)

# Format y-axis to show numbers with commas
fig.update_yaxes(tickformat=',')


# Add value labels on bars
fig.update_traces(
    texttemplate='%{y:,}',
    textposition='outside'
)

fig.show()

7. Which months have the highest passenger traffic?
•Columns: Month, Passenger Count
•Graph: Bar Chart
•Description: Show passenger counts for each month to identify peak travel periods.

In [57]:
# Group by Month and sum passenger counts
monthly_totals = df.groupby('Month')['Passenger Count'].sum().reset_index()

# Define the correct month order for sorting
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
              'July', 'August', 'September', 'October', 'November', 'December']

# Convert Month to categorical with proper ordering
monthly_totals['Month'] = pd.Categorical(monthly_totals['Month'], categories=month_order, ordered=True)
monthly_totals = monthly_totals.sort_values('Month')

# Create bar chart
fig = px.bar(
    monthly_totals,
    x='Month',
    y='Passenger Count',
    title='📅 Monthly Passenger Traffic',
    labels={'Passenger Count': 'Total Passengers', 'Month': 'Month'},
    color='Passenger Count',
    color_continuous_scale='viridis'
)


fig.update_layout(
    template='plotly_white',
    title_x=0.5,
    xaxis_tickangle=45,
    height=500
)

# Format y-axis to show numbers with commas
fig.update_yaxes(tickformat=',')

# Add value labels on bars
fig.update_traces(
    texttemplate='%{y:,}',
    textposition='outside'
)

fig.show()

8. How have adjusted passenger counts changed over time?
•Columns: Activity Period, Adjusted Passenger Count, Year, Month
•Graph: Line Chart
•Description: Plot adjusted passenger counts over time to see trends and adjustments

In [58]:
# Group by Activity Period and sum adjusted passenger counts
adjusted_totals = df.groupby(['Activity Period', 'Activity Period Label'])['Adjusted Passenger Count'].sum().reset_index()

# Create line chart for adjusted passenger counts
fig = px.line(
    adjusted_totals,
    x='Activity Period Label',
    y='Adjusted Passenger Count',
    title='📈 Adjusted Passenger Counts Over Time',
    labels={'Adjusted Passenger Count': 'Adjusted Passengers', 'Activity Period Label': 'Date'},
    markers=True
)


fig.update_layout(
    template='plotly_white',
    title_x=0.5,
   xaxis_tickangle= -60,
    height=500
)

# Format y-axis to show numbers with commas
fig.update_yaxes(tickformat=',')

# Add trendline
fig.add_scatter(
    x=adjusted_totals['Activity Period Label'],
    y=adjusted_totals['Adjusted Passenger Count'].rolling(window=3).mean(),
    mode='lines',
    line=dict(dash='dot', color='red', width=2),
    name='3-Month Moving Average'
)

fig.show()

9. Which boarding areas are the busiest?
•Columns: Boarding Area, Passenger Count
•Graph: Bar Chart or Heatmap
•Description: Compare passenger counts for different boarding areas.

In [59]:
# Group by Boarding Area and sum passenger counts
boarding_totals = df.groupby('Boarding Area')['Passenger Count'].sum().reset_index()

# Sort by passenger count in descending order
boarding_totals = boarding_totals.sort_values('Passenger Count', ascending=False)

# Create vertical bar chart
fig = px.bar(
    boarding_totals,
    x='Boarding Area',
    y='Passenger Count',
    title='🚪 Busiest Boarding Areas',
    labels={'Passenger Count': 'Total Passengers', 'Boarding Area': 'Boarding Area'},
    color='Passenger Count',
    color_continuous_scale='reds'
)


fig.update_layout(
    template='plotly_white',
    title_x=0.5,
   # xaxis_tickangle= -45,
    height=500
)

# Format y-axis to show numbers with commas
fig.update_yaxes(tickformat=',')

# Add value labels on bars
fig.update_traces(
    texttemplate='%{y:,}',
    textposition='outside'
)

fig.show()

10. What is the trend of international vs. domestic passenger traffic?
•Columns: Activity Type Code, Passenger Count, Year, Month
•Graph: Line Chart or Stacked Bar Chart
•Description: Compare trends in international vs. domestic passenger counts over time

In [60]:
# Group by Activity Period and GEO Summary
geo_trends = df.groupby(['Activity Period', 'Activity Period Label', 'GEO Summary'])['Passenger Count'].sum().reset_index()

# Create line chart comparing domestic vs international trends
fig1 = px.line(
    geo_trends,
    x='Activity Period Label',
    y='Passenger Count',
    color='GEO Summary',
    title='🌍 International vs Domestic Passenger Trends',
    labels={'Passenger Count': 'Total Passengers', 'Activity Period Label': 'Date'},
    markers=True,
    color_discrete_map={'Domestic': '#1f77b4', 'International': '#ff7f0e'}
)

fig1.update_layout(
    template='plotly_white',
    title_x=0.5,
    height=500
)
fig1.update_yaxes(tickformat=',')
fig1.show()